allow-lan: false

mode: rule

log-level: info

ipv6: true

external-controller: 127.0.0.1:9090

external-ui: dashboard

external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

profile:
  store-selected: true
  store-fake-ip: true

unified-delay: true

tcp-concurrent: true

dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: false
  listen: 127.0.0.1:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter:
    - RULE-SET,real-ip,real-ip
    - MATCH,fake-ip
  fake-ip-filter-mode: rule
  respect-rules: false
  default-nameserver: [system]
  nameserver-policy:
    "rule-set:direct-domain": [system]
  proxy-server-nameserver: [https://dns.alidns.com/dns-query]
  proxy-server-nameserver-policy: []
  nameserver: [https://dns.alidns.com/dns-query]

sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    QUIC:
      ports: [443, 8443]
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]

mixed-port: 7892

tun:
  enable: true
  stack: mixed
  device: mihomo
  auto-route: true
  auto-detect-interface: true
  dns-hijack: [any:53, tcp://any:53]
  strict-route: true
  mtu: 1440

proxies:

proxies-custom: &proxies-custom ["DIRECT"]

proxy-group-custom: &proxy-group-custom
  type: select

proxy-group-region: &proxy-group-region
  type: url-test
  url: https://cp.cloudflare.com/generate_204
  interval: 1800
  timeout: 3000
  max-failed-times: 3
  include-all-proxies: true
  tolerance: 30

proxy-groups:
  - name: GAM
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/gam.svg

  - name: VDO
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/vdo.svg

  - name: AIS
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/ais.svg

  - name: CRP
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/crp.svg

  - name: FIN
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/fin.svg

  - name: ECM
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/ecm.svg

  - name: GGL
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/ggl.svg

  - name: MSF
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/msf.svg

  - name: APL
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/apl.svg

  - name: PRX
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/policies/svg/prx.svg

  - name: YT
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/yt.svg

  - name: TG
    <<: *proxy-group-custom
    proxies: *proxies-custom
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/tg.svg

  - name: HK
    <<: *proxy-group-region
    filter: HK
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/hk.svg

  - name: TW
    <<: *proxy-group-region
    filter: TW
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/tw.svg

  - name: JP
    <<: *proxy-group-region
    filter: JP
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/jp.svg

  - name: SG
    <<: *proxy-group-region
    filter: SG
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/sg.svg

  - name: US
    <<: *proxy-group-region
    filter: US
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/us.svg

rule-provider-domain: &rule-provider-domain
  type: http
  interval: 86400
  proxy: DIRECT
  behavior: domain
  format: mrs

rule-provider-ipcidr: &rule-provider-ipcidr
  type: http
  interval: 86400
  proxy: DIRECT
  behavior: ipcidr
  format: mrs

rule-provider-classical: &rule-provider-classical
  type: http
  interval: 86400
  proxy: DIRECT
  behavior: classical

rule-providers:
  real-ip:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/real-ip.mrs
    path: ./rule-providers/real-ip.mrs

  direct-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/direct-domain.mrs
    path: ./rule-providers/direct-domain.mrs

  direct-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/direct-ipcidr.mrs
    path: ./rule-providers/direct-ipcidr.mrs

  direct-classical:
    <<: *rule-provider-classical
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/direct-classical.yaml
    path: ./rule-providers/direct-classical.yaml

  yt-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/yt-domain.mrs
    path: ./rule-providers/yt-domain.mrs

  sp-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/sp-domain.mrs
    path: ./rule-providers/sp-domain.mrs

  tg-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/tg-domain.mrs
    path: ./rule-providers/tg-domain.mrs

  tg-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/tg-ipcidr.mrs
    path: ./rule-providers/tg-ipcidr.mrs

  gh-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/gh-domain.mrs
    path: ./rule-providers/gh-domain.mrs

  nk-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/nk-domain.mrs
    path: ./rule-providers/nk-domain.mrs

  gam-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/gam-cn-domain.mrs
    path: ./rule-providers/gam-cn-domain.mrs

  gam-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/gam-domain.mrs
    path: ./rule-providers/gam-domain.mrs

  vdo-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/vdo-domain.mrs
    path: ./rule-providers/vdo-domain.mrs

  vdo-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/vdo-ipcidr.mrs
    path: ./rule-providers/vdo-ipcidr.mrs

  ais-us-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ais-us-domain.mrs
    path: ./rule-providers/ais-us-domain.mrs

  ais-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ais-domain.mrs
    path: ./rule-providers/ais-domain.mrs

  crp-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/crp-domain.mrs
    path: ./rule-providers/crp-domain.mrs

  crp-classical:
    <<: *rule-provider-classical
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/crp-classical.yaml
    path: ./rule-providers/crp-classical.yaml

  fin-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/fin-domain.mrs
    path: ./rule-providers/fin-domain.mrs

  ecm-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ecm-domain.mrs
    path: ./rule-providers/ecm-domain.mrs

  ecm-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ecm-ipcidr.mrs
    path: ./rule-providers/ecm-ipcidr.mrs

  ggl-us-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ggl-us-domain.mrs
    path: ./rule-providers/ggl-us-domain.mrs

  ggl-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ggl-cn-domain.mrs
    path: ./rule-providers/ggl-cn-domain.mrs

  ggl-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ggl-domain.mrs
    path: ./rule-providers/ggl-domain.mrs

  ggl-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ggl-ipcidr.mrs
    path: ./rule-providers/ggl-ipcidr.mrs

  msf-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/msf-cn-domain.mrs
    path: ./rule-providers/msf-cn-domain.mrs

  msf-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/msf-domain.mrs
    path: ./rule-providers/msf-domain.mrs

  apl-ex-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apl-ex-domain.mrs
    path: ./rule-providers/apl-ex-domain.mrs

  apl-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apl-cn-domain.mrs
    path: ./rule-providers/apl-cn-domain.mrs

  apl-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apl-domain.mrs
    path: ./rule-providers/apl-domain.mrs

  apl-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apl-ipcidr.mrs
    path: ./rule-providers/apl-ipcidr.mrs

  china-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/china-domain.mrs
    path: ./rule-providers/china-domain.mrs

  china-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/china-ipcidr.mrs
    path: ./rule-providers/china-ipcidr.mrs

rules:
  - RULE-SET,direct-domain,DIRECT
  - RULE-SET,direct-ipcidr,DIRECT,no-resolve
  - RULE-SET,direct-classical,DIRECT
  - RULE-SET,yt-domain,YT
  - RULE-SET,sp-domain,US
  - RULE-SET,tg-domain,TG
  - RULE-SET,tg-ipcidr,TG,no-resolve
  - RULE-SET,gh-domain,HK
  - RULE-SET,nk-domain,US
  - RULE-SET,gam-cn-domain,DIRECT
  - RULE-SET,gam-domain,GAM
  - RULE-SET,vdo-domain,VDO
  - RULE-SET,vdo-ipcidr,VDO,no-resolve
  - RULE-SET,ais-us-domain,US
  - RULE-SET,ais-domain,AIS
  - RULE-SET,crp-domain,CRP
  - RULE-SET,crp-classical,CRP
  - RULE-SET,fin-domain,FIN
  - RULE-SET,ecm-domain,ECM
  - RULE-SET,ecm-ipcidr,ECM,no-resolve
  - RULE-SET,ggl-us-domain,US
  - RULE-SET,ggl-cn-domain,DIRECT
  - RULE-SET,ggl-domain,GGL
  - RULE-SET,ggl-ipcidr,GGL,no-resolve
  - RULE-SET,msf-cn-domain,DIRECT
  - RULE-SET,msf-domain,MSF
  - RULE-SET,apl-ex-domain,APL
  - RULE-SET,apl-cn-domain,DIRECT
  - RULE-SET,apl-domain,APL
  - RULE-SET,apl-ipcidr,APL,no-resolve
  - RULE-SET,china-domain,DIRECT
  - RULE-SET,china-ipcidr,DIRECT,no-resolve
  - MATCH,PRX
