[[rename_node]]
match = "^(瑞士|Switzerland)"
replace = "🇨🇭 CH-XXX KU-IEPL"

[[rename_node]]
match = "^(德国|Germany)"
replace = "🇩🇪 DE-XXX KU-IEPL"

[[rename_node]]
match = "^(澳大利亚|Australia)"
replace = "🇦🇺 AU-XXX KU-IEPL"

[[rename_node]]
match = "^(中国香港特别行政区|Hong Kong, China \\(SAR\\)|Hong Kong)"
replace = "🇭🇰 HK-XXX KU-IEPL"

[[rename_node]]
match = "^(荷兰|Netherlands)"
replace = "🇳🇱 NL-XXX KU-IEPL"

[[rename_node]]
match = "^(新加坡|Singapore)"
replace = "🇸🇬 SG-XXX KU-IEPL"

[[rename_node]]
match = "^(英国|United Kingdom)"
replace = "🇬🇧 GB-XXX KU-IEPL"

[[rename_node]]
match = "^(美国|United States)"
replace = "🇺🇸 US-XXX KU-IEPL"

[[rename_node]]
match = "^(韩国|Korea \\(Republic of\\)|South Korea)"
replace = "🇰🇷 KR-XXX KU-IEPL"

[[rename_node]]
match = "^(日本|Japan)"
replace = "🇯🇵 JP-XXX KU-IEPL"

[[rename_node]]
match = "^(法国|France)"
replace = "🇫🇷 FR-XXX KU-IEPL"

[[rename_node]]
match = "^(印度|India)"
replace = "🇮🇳 IN-XXX KU-IEPL"

[[rename_node]]
match = "^(台湾|Taiwan)"
replace = "🇹🇼 TW-XXX KU-IEPL"
